---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: plex 
  labels:
    app: plex
spec:
  replicas: 1
  selector:
    matchLabels:
      app: plex
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: plex
    spec:
#      hostNetwork: true
      containers:
      - name: plex 
        image: plexinc/pms-docker:latest 
        imagePullPolicy: Always 
        ports:
        - containerPort: 32400
          name: web-ui 
          protocol: TCP
        - containerPort: 3005
          protocol: TCP
        - containerPort: 8324 
          protocol: TCP
        - containerPort: 32469
          protocol: TCP
        - containerPort: 1900 
          protocol: TCP
        - containerPort: 32410 
          protocol: TCP
        - containerPort: 32412 
          protocol: TCP
        - containerPort: 32413 
          protocol: TCP
        - containerPort: 32414 
          protocol: TCP
        env:
        - name: PLEX_UID
          value: "444"
        - name: GROUP_UID
          value: "321"
        - name: UMASK_SET
          value: "002"
        - name: VERSION
          value: docker
        - name: ALLOWED_NETWORKS
          value: 192.168.0.1/24 
        - name: "CLAIM"
          value: claim-RMjNee5yKwRmNj36pEWz 
        volumeMounts:
        - name: plex
          mountPath: /config
          subPath: plex/config
        - name: media
          mountPath: /data/media
      volumes:
      - name: plex 
        persistentVolumeClaim:
          claimName: synology-plex
      - name: media
        persistentVolumeClaim:
          claimName: synology-media
