---
apiVersion: v1
kind: PersistentVolume
metadata: 
  name: synology-plex
spec:
  capacity:
    storage: 15Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: synology
  persistentVolumeReclaimPolicy: Retain
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    server: synology.home
    path: "/volume1/k8s-pv01"
