apiVersion: v1
kind: Service
metadata:
  name: plex
  namespace: default
spec:
  type: NodePort
  ports:
  - name: plex
    nodePort: 32400
    port: 32400
    protocol: TCP
    targetPort: 32400
  - name: plex-3005
    targetPort: 3005
    protocol: TCP
    port: 3005
  - name: plex-8324
    targetPort: 8324
    protocol: TCP
    port: 8324
  - name: plex-32469
    targetPort: 32469
    protocol: TCP
    port: 32469
  - name: plex-1900
    targetPort: 1900
    protocol: UDP
    port: 1900
  - name: plex-32410
    targetPort: 32410
    protocol: UDP
    port: 32410
  - name: plex-32412
    targetPort: 32412
    protocol: UDP
    port: 32412
  - name: plex-32413
    targetPort: 32413
    protocol: UDP
    port: 32413
  - name: plex-32414
    targetPort: 32414
    protocol: UDP
    port: 32414
  selector:
    app: plex
  externalIPs:
  - 192.168.0.211
  - 192.168.0.221
  - 192.168.0.222
  - 192.138.0.223
