---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: synology-plex
  namespace: default
spec:
  accessModes:
  - ReadWriteMany
  storageClassName: synology
  resources:
    requests:
      storage: 15Gi
